### ISSUE TITLE
ネットワークモードでサーバーアナウンスが設定に依らず行われる

### ISSUE THREAD

**Issue by kuroitori-bunko** [teamhimeh/simutrans#30]
こんにちは、ネットワークモード（サーバー側）でのバグと思わしき事象を発見致しました。
内容としては、セーブデータ読み込み時にサーバーとして読み込むと、simuconf.tabの設定に依らずサーバーのアナウンス（http://servers.simutrans.org/list） がなされるというものです。
128JPで現象を確認後、ノーマルの128にてOTRPv23.4とnightaly（R8928）双方で、検証したところ、引数(-server)とした場合は共にアナウンスはされませんでした。
一方、OTRPにてセーブデータを読み込みサーバーとしたところアナウンスがなされました。
以上の結果のもと、OTRP側の不具合と推認されるため、こちらにて報告の方をさせていただきます。

**Comment by ahakuoku** [comment]
こんにちは。モデレーターのahakuokuです。
当該のバグですが、再現性がなく、さらにOTRPとStandard双方でサーバーのアナウンスをする設定にしていてもアナウンスがされない現象が発生しており、このことからこのバグはStandardでも発生するものと思われます。
