### ISSUE TITLE
The value -100 is used for 'unknown height', which can appear in maps.

### ISSUE THREAD

**Issue by teamhimeh** [teamhimeh/simutrans#4]
The value -100 is used for 'unknown height', which can appear in maps. You could use sint16 and initialize with an unreachable value (like -200).

**Comment by Dwachs** [comment]
or initialize properly (e.g., z-coordinate of first tile of building to be replaced)

**Comment by teamhimeh** [comment]
Standard: https://github.com/teamhimeh/simutrans/commit/10d455f1d659a171247418f31b25de2d29d1c5f5
After height check was abolished by not restoring slope.
