### ISSUE TITLE
NetSimutransでプレイヤー入室時に解結される

### ISSUE THREAD

**Issue by Kai-Z-JP** [teamhimeh/simutrans#46]
標題の通りバグと思わしき事象を発見したため、以下の通り報告させて頂きます。

# 環境
OTRP v29.5

# 再現手順

## 路線概要
- 編成イ A駅---B駅---C駅---D駅---(中継点1)---E駅---F駅
- 編成ロ A駅---B駅---C駅---D駅---(中継点1)---E駅---G駅
A-E駅間を編成イが先頭になるようにE駅で連結
<- A駅 (イ)+(ロ) E駅->

## 不具合概要
　E駅からD駅へ向かって走行中、E駅から中継点1の間を走行中にプレイヤーが入室すると、D駅到着時に編成ロの次の停車駅がC駅ではなくB駅となり連結が解除される。
　また、D-E駅間に中継点を増やすとその分だけ編成ロの次の停車駅が先の駅になる。(例: 中継点2を挿入するとD駅到着時に編成ロの次の停車駅がA駅になる。)

よろしくおねがいします。

**Comment by ahakuoku** [comment]
OTRP運営チームのahakuokuです。
まず、返事が遅くなり申し訳ございません。

OTRPv29_6において当該不具合の再現に成功しました。
なお、次の停車駅が勝手に変わるのは実際にはロード直後でした。

OTRPはすでに開発を終了していることから、修正の保証はできませんが、開発者まで報告させていただけます。

**Comment by teamhimeh** [comment]
https://github.com/teamhimeh/simutrans/commit/5a8c5f518fad478dc35dfa41cd0d0679ed774389 で修正しました。v31で反映される予定です。
