### ISSUE TITLE
in hausbauer_t::get_city_building_from_list tiles are visited more than once.

### ISSUE THREAD

**Issue by teamhimeh** [teamhimeh/simutrans#6]
To calculate replaced_level_per_a_tile in hausbauer_t::get_city_building_from_list tiles are visited more than once. Calculations can be restructured for performance.

**Comment by teamhimeh** [comment]
This issue is very minor and has no priority.

**Comment by Dwachs** [comment]
An idea to overcome this: In the calculation of possible sizes in simcity.cc one can already compute the level of buildings that need to be replaced. This could then be given to hausbauer.cc for building selection. (I agree about priority)
